export const downloadPDF = async () => {
    const htmlContent = `
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, sans-serif;
        }
        body {
            background-color: #f5f7fa;
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        .container {
            width: 350px;
            background-color: #fff;
            border-radius: 15px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }
        .header {
            background: linear-gradient(to right, #0B9FD5, #284374);
            color: #fff;
            padding: 15px;
            border-radius: 10px;
            text-align: flex-start;
            font-weight: bold;
        }
        .user-info {
            margin-top: 10px;
            padding: 10px;
            border-radius: 10px;
            display: flex;
            justify-content: space-between;
        }
        .user-info div {
            text-align: center;
            font-size: 14px;
        }
        .health-age {
            margin-top: 15px;
            background: #fff8e5;
            padding: 15px;
            border-radius: 10px;
            text-align: center;
        }
        .age-numbers {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
        }
        .age-box {
            width: 30%;
            padding: 10px;
            background-color: #eef2f6;
            border-radius: 10px;
            text-align: center;
            font-size: 16px;
            font-weight: bold;
        }
      .text-p{
      font-size: 12px;
            font-weight: 300;
      }
        .age-box:nth-child(2) {
            background-color: #dff5e7;
        }
        .recommendations {
            margin-top: 20px;
        }
        .recommendations h3 {
            font-size: 16px;
            margin-bottom: 10px;
        }
        .recommendation {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            font-size: 14px;
        }
      .separator {
    width: 100%;
      margin-top:10px;
    border-width: 1px;  
    border-color: white;
    border-style: solid; 
}

      .check-icon-container {
      width:40px;
      }
        .check-icon {
            width: 20px;
            height: 20px;
            background-color: #4caf50;
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 14px;
            margin-right: 10px;
        }
    

    </style>
</head>
<body>

    <div class="container">
      <div class="header"><p class="text-p">Customized report for: </p><br><strong>${userName}</strong>
          <div class="separator"></div>
          <div class="user-info">
            <div ><p class="text-p">Gender: </p><br><strong>${userGender}</strong></div>
            <div><p class="text-p">Age:</p><br><strong>${userAge}</strong></div>
            <div><p class="text-p">Height:</p><br><strong>${userHeight}</strong></div>
              <div><p class="text-p">Weight:</p><br><strong>${userWeight}</strong></div>
        </div></div>



        <div class="health-age">
            <p>Your health age is <strong>22</strong> vs your actual age of <strong>27</strong></p>
            <div class="age-numbers">
              <div class="age-box">${userAge} <br><p class="text-p">Current Age</p></div>
                <div class="age-box">${healthAge} <br><p class="text-p">Health Age</p></div>
                <div class="age-box">${potentialAge} <br><p class="text-p">Potential Age</p></div>
            </div>
        </div>

        <p style="margin-top: 15px; font-size: 13px;">
            Several large research studies, including the well-known Alameda County Study and the Adventist Health Studies, reveal a strong correlation between the health habits listed below and one’s risk of disease/death. 
        </p>

        <div class="recommendations">
            <h3>Recommendations</h3>
           ${generateRecommendationsHTML}
        </div>
              <div class="last-div"><p class="text-p">This Pdf is Generated by Health Age App</p></div>
    </div>
</body>
</html>
    `;
    try {
      // Generate PDF
      const options = {
        html: htmlContent,
        fileName: "report",
        directory: "Documents",
      };

      const pdf = await RNHTMLtoPDF.convert(options);

      // Check if filePath is defined
      if (!pdf.filePath) {
        throw new Error("PDF generation failed: filePath is undefined");
      }

      // Save the PDF to the device
      const destinationPath = `${RNFS.ExternalStorageDirectoryPath}/Download/report.pdf`;
      await RNFS.copyFile(pdf.filePath, destinationPath);

      alert("PDF downloaded successfully!");
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("An error occurred while generating the PDF.");
    }
  };

